### ISSUE TITLE
Could you please explain, a bit, the design of hfx-bus?

### ISSUE THREAD

**Issue by adioanca** [exocet-engineering/hfx-bus#6]
Hi,

Could you please explain the general flow in terms of Redis structures and key names?

I see a Redis Stream ("ping"), okay..., looking through the code I also see some pieces related to PubSub but `PUBSUB CHANNELS *` doesn't list anything.  
A short architecture paragraph would be great.  
...something like https://www.slideshare.net/RedisLabs/redisconf18-building-lightweight-microservices-using-redis starting from slide 57

Thank you

PS: also 'hfxbus' is said to be the default namespace, shouldn't the stream name be `hfxbus:ping` ? or is this related to NodeJs/EventEmitter/RedisConsumerGroups/PubSub... what's the purpose of `heartz`?

> I'm just learning Redis & NodeJS & Javascript & Co... so apologies for the some of the, maybe, dumb questions

**Comment by vflopes** [comment]
Cool feature for docs! I'll work on some specific specification about the architecture. I think a sequence diagram would be nice too.

Currently HFXBus only puts the prefix on consumer group name, this is a design choice to allow multiple consumer groups to consume the same stream. If the stream name was prefixed with the namespace the stream would be bounded to the context of groups in that namespace. On event-sourcing environments the current behavior is very useful because multiple services (consumers) can read the same message to do their business logic.

And don't think you're asking dumb questions, these are very relevant questions (the architecture of HFXBus x Redis really needs some attention on docs). Thanks!
